services:
    mdbook:
        container_name: mdbook
        image: peaceiris/mdbook:v0.5.0
        stdin_open: true
        tty: true
        ports:
            - 3000:3000
            - 3001:3001
        volumes:
            - ${PWD}/..:/repo
        working_dir: /repo/docs
        command:
            - serve
            - --hostname
            - "0.0.0.0"
